from .custom_path_loader import SpectrogramCustomPathDataset
from .direct_loader import SpectrogramDirectDataset
from .multiple_loader import SpectrogramMultipleDataset
from .named_loader import SpectrogramNamedDataset
from .single_loader import SpectrogramSingleDataset
from .base_loader import SpectrogramBaseDataset